apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ide

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ide-workspace

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ide
      namespace: ide
      labels:
        name: ide

  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: ide-cluster-view
      labels:
        name: ide
    rules:
      - apiGroups: [ '*' ]
        resources: [ '*' ]
        verbs: [ 'get', 'list', 'watch' ]
      - nonResourceURLs: [ '*' ]
        verbs: [ 'get', 'list', 'watch' ]
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: ide-cluster-view
      labels:
        name: ide
    roleRef:
      kind: ClusterRole
      name: ide-cluster-view
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: ide
        namespace: ide

  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: Role
    metadata:
      name: ide-workspace-admin
      namespace: ide-workspace
      labels:
        name: ide
    rules:
      - apiGroups: [ '*' ]
        resources: [ '*' ]
        verbs: [ '*' ]
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: ide-workspace-admin
      namespace: ide-workspace
      labels:
        name: ide
    roleRef:
      kind: Role
      name: ide-workspace-admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: ide
        namespace: ide

  - apiVersion: v1
    kind: Service
    metadata:
      name: ide
      namespace: ide
      labels:
        name: ide
    spec:
      selector:
        name: ide
      ports:
      - name: http
        port: 80
        targetPort: 8080
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ide
      namespace: ide
      annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.frontend.passHostHeader: "false"
    spec:
      backend:
        serviceName: ide
        servicePort: http
      # TODO we can actually setup DNS and TLS with Let's Encrypt and external DNS
      # https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/gke.md
      # and use training.weave.works. DNS zone
      rules:
        - http:
            paths:
              - path: /
                backend:
                  serviceName: ide
                  servicePort: http
              - path: /app/metrics-demo
                backend:
                  ## todo use ide-workspace namespaces
                  serviceName: metrics-demo
                  servicePort: http

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ide-workspace-data
      namespace: ide
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 2Gi

  - apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: ide
      namespace: ide
      labels:
        name: ide
    spec:
      template:
        metadata:
          labels:
            name: ide
        spec:
          serviceAccount: ide
          restartPolicy: Always
          terminationGracePeriodSeconds: 10
          initContainers:
            - name: git-clone
              image: errordeveloper/k9c@sha256:ad69086ac28b91c745ecd8be2d21e1f1630d81c9eeb6967338c9f73794780475
              command: [ '/bin/sh', '-c', 'test -d /workspace/app || git clone https://github.com/bricef/metrics-demo' ]
              volumeMounts:
                - name: ide-workspace-data
                  mountPath: /workspace
          containers:
            - name: ide
              image: errordeveloper/k9c@sha256:ad69086ac28b91c745ecd8be2d21e1f1630d81c9eeb6967338c9f73794780475
              imagePullPolicy: IfNotPresent
              ports:
                - name: http
                  containerPort: 8080
              livenessProbe:
                httpGet:
                  port: http
                  path: /ide.html
                  httpHeaders:
                    - name: Authorization
                      value: 'Basic dXNlcm5hbWU6cGFzc3dvcmQ='
                initialDelaySeconds: 30
                periodSeconds: 5
              readinessProbe:
                httpGet:
                  port: http
                  path: /ide.html
                  httpHeaders:
                    - name: Authorization
                      value: 'Basic dXNlcm5hbWU6cGFzc3dvcmQ='
                initialDelaySeconds: 5
                periodSeconds: 1
              volumeMounts:
                - name: ide-workspace-data
                  mountPath: /workspace
                - name: dockersocket
                  mountPath: /var/run/docker.sock
          volumes:
            - name: ide-workspace-data
              persistentVolumeClaim:
                claimName: ide-workspace-data
            - name: dockersocket
              hostPath:
                path: /var/run/docker.sock
