apiVersion: v1
kind: List
items:

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: grafana
      namespace: weave
      labels:
        app: grafana
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: grafana
        spec:
          volumes:
            - name: datasources
              configMap:
                name: grafana-datasources
          containers:
            - image: grafana/grafana:5.0.0-beta2
              name: grafana
              imagePullPolicy: Always
              ports:
                - name: grafana
                  containerPort: 3000
              env:
                #- name: GF_SERVER_ROOT_URL
                #  value: 'http://grafana.weave.svc.cluster.local/grafana'
                - name: GF_SERVER_ROOT_URL
                  value:
                    kubegen.String.Join:
                      - 'http://'
                      - {kubegen.String.Lookup: external-dns/domain}
                      - '/grafana'
                - name: GF_SECURITY_ADMIN_USER
                  value: {kubegen.String.Lookup: username}
                - name: GF_SECURITY_ADMIN_PASSWORD
                  value: {kubegen.String.Lookup: password}
              volumeMounts:
                - name: datasources
                  mountPath: /etc/grafana/provisioning/datasources
            #- name: gfdatasource
            #  image: weaveworks/gfdatasource:master-1708580
            #  imagePullPolicy: Always
            #  args:
            #    - kubegen.String.Join:
            #      - '--grafana-url=http://'
            #      - {kubegen.String.Lookup: username}
            #      - ':'
            #      - {kubegen.String.Lookup: password}
            #      - '@127.0.0.1:3000/api'
            #    - --data-source-url=http://prometheus.weave.svc.cluster.local/prometheus
            #    - --access=direct
            #    - --update-interval=3600

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-datasources
      namespace: weave
      labels:
        app: grafana
    data:
      prometheus.yaml:
        kubegen.String.AsYAML:
          apiVersion: 1
          datasources: 
            - name: prometheus
              type: prometheus
              access: direct
              url: http://prometheus.weave.svc.cluster.local/prometheus
              orgId: 1
              version: 1
              isDefault: true
              editable: false

  - apiVersion: v1
    kind: Service
    metadata:
      name: grafana
      namespace: weave
      labels:
        app: grafana
    spec:
      type: ClusterIP
      ports:
        - name: grafana
          protocol: TCP
          port: 80
          targetPort: 3000
      selector:
        app: grafana
