apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: external-dns-controller
      namespace: kube-system

  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: external-dns-controller
    rules:
      - apiGroups:
          - ""
        resources:
          - services
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - ingresses
        verbs:
          - get
          - list
          - watch
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: external-dns-controller
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: external-dns-controller
    subjects:
    - kind: ServiceAccount
      name: external-dns-controller
      namespace: kube-system
      
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: external-dns-controller
      namespace: kube-system
    spec:
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            k8s-app: external-dns
            name: external-dns
        spec:
          serviceAccount: external-dns-controller
          containers:
          - name: external-dns
            image: registry.opensource.zalan.do/teapot/external-dns:v0.4.8
            args:
            - --source=service
            - --source=ingress
            # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
            - --policy=upsert-only
            # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
            - --provider=google
            - --registry=txt
            - kubegen.String.Join:
              - --txt-owner-id=
              - kubegen.String.Lookup: username
            - kubegen.String.Join:
              - --domain-filter=
              - kubegen.String.Lookup: external-dns/zone
            - kubegen.String.Join:
              - --google-project=
              - kubegen.String.Lookup: external-dns/google-project
