apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ide
  namespace: {kubegen.String.Lookup: namespaces/ide}
  annotations:
    kubernetes.io/ingress.class: {kubegen.String.Lookup: ingress/class}
    traefik.frontend.passHostHeader: "false"
spec:
  backend:
    serviceName: ide
    servicePort: http
  # TODO we can actually setup DNS and TLS with Let's Encrypt and external DNS
  # https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/gke.md
  # and use training.weave.works. DNS zone
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ide
              servicePort: http
          - path: /app/metrics-demo
            backend:
              ## TODO use ide-workspace namespaces
              serviceName: metrics-demo
              servicePort: http
