apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ide-workspace-data
  namespace: {kubegen.String.Lookup: namespaces/ide}
  labels:
    name: ide
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi # TODO parametrize
