apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: List
    items:

    - apiVersion: v1
      kind: Namespace
      metadata:
        name: {kubegen.String.Lookup: namespaces/ide}

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ide
        namespace: {kubegen.String.Lookup: namespaces/ide}
        labels:
          name: ide

    - apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRole
      metadata:
        name:
          kubegen.String.Join:
            - {kubegen.String.Lookup: namespaces/ide}
            - -cluster-view
        labels:
          name: ide
      rules:
        - apiGroups: [ '*' ]
          resources: [ '*' ]
          verbs: [ 'get', 'list', 'watch' ]
        - nonResourceURLs: [ '*' ]
          verbs: [ 'get', 'list', 'watch' ]

  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name:
        kubegen.String.Join:
          - {kubegen.String.Lookup: namespaces/ide}
          - -cluster-view
      labels:
        name: ide
    roleRef:
      kind: ClusterRole
      name:
        kubegen.String.Join:
          - {kubegen.String.Lookup: namespaces/ide}
          - -cluster-view
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: ide 
        namespace: {kubegen.String.Lookup: namespaces/ide}

  - apiVersion: v1
    kind: List
    items:

    - apiVersion: v1
      kind: Namespace
      metadata:
        name: {kubegen.String.Lookup: namespaces/workspace}

    - apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: Role
      metadata:
        name:
          kubegen.String.Join:
            - {kubegen.String.Lookup: namespaces/workspace}
            - -workspace-admin
        namespace: {kubegen.String.Lookup: namespaces/workspace}
        labels:
          name: ide
      rules:
        - apiGroups: [ '*' ]
          resources: [ '*' ]
          verbs: [ '*' ]

    - apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: RoleBinding
      metadata:
        name:
          kubegen.String.Join:
            - {kubegen.String.Lookup: namespaces/workspace}
            - -workspace-admin
        namespace: {kubegen.String.Lookup: namespaces/workspace}
        labels:
          name: ide
      roleRef:
        kind: Role
        name:
          kubegen.String.Join:
            - {kubegen.String.Lookup: namespaces/workspace}
            - -workspace-admin
        apiGroup: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: ide
          namespace: {kubegen.String.Lookup: namespaces/ide}

